name: "Game Master Assistant"
description: "AI assistant for tabletop RPG game masters"

# Default LLM configuration
configuration:
  default_llm:
    name: "default_model"
    provider: "huggingface"
    model: "mistralai/Mistral-7B-Instruct-v0.2"
    parameters:
      temperature: 0.7
      max_length: 1024
      top_p: 0.95

  # Alternative models
  models:
    - name: "azure_gpt4"
      provider: "azure_openai"
      model: "gpt-4"
      api_version: "2023-05-15"
      deployment_name: "gpt4-deployment"
      parameters:
        temperature: 0.5
        max_tokens: 800
    
    - name: "claude"
      provider: "anthropic"
      model: "claude-2.1"
      parameters:
        temperature: 0.7
        max_tokens_to_sample: 2000

# Define workflows
workflows:
  # RAG workflow for general knowledge questions
  - name: "rag_workflow"
    description: "Standard RAG workflow for general questions"
    type: "rag"
    model: "default_model"  # Use default model
    activation:
      keywords: ["what", "who", "how", "when", "where", "why"]
      priority: 1
      default: false
    tools:
      - name: "rag_tool"
        parameters:
          top_k: 3

  # Graph workflow for relationship questions
  - name: "graph_workflow"
    description: "Graph query workflow for relationship questions"
    type: "graph"
    model: "azure_gpt4"  # Use Azure OpenAI for relationships
    activation:
      keywords: ["related", "connection", "relationship", "between", "linked"]
      priority: 2
      default: false
    components:
      - "graph_query_handler"

  # Creative workflow
  - name: "creative_workflow"
    description: "Creative writing and ideation workflow"
    type: "rag"
    model: "claude"  # Use Claude for creative tasks
    activation:
      keywords: ["create", "generate", "idea", "design", "story"]
      priority: 3
      default: false
    tools:
      - name: "rag_tool"
        parameters:
          top_k: 5
          query_type: "creative"

  # Hybrid workflow as default fallback
  - name: "hybrid_workflow"
    description: "Hybrid workflow combining RAG and graph queries"
    type: "hybrid"
    activation:
      keywords: []
      priority: 0
      default: true
    tools:
      - name: "rag_tool"
        parameters:
          top_k: 3
      - name: "graph_query_tool"
        parameters: {}
